# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course'),
        ('course', '0004_document_topic'),
    ]

    operations = [
    ]
