# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_merge_20170228_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
